version: "3"

services:
  db:
    image: mariadb:latest
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/entrypoint/:/docker-entrypoint-initdb.d/

    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 4040:80
    # volumes:
    #   - ./phpmyadmin/sessions:/sessions
